// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back.Models
{
    public partial class Atencion
    {
        public int IdAtencion { get; set; }
        public int? IdMascota { get; set; }
        public DateTime? Fecha { get; set; }
        public string Descripcion { get; set; }
        public double? Importe { get; set; }
        public virtual Mascota IdMascotaNavigation { get; set; }
    }
}